import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const griftSans = localFont({
  src: [
    {
      path: "./fonts/grift-thin.otf",
      weight: "200",
      style: "normal",
    },
    {
      path: "./fonts/grift-light.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/grift-regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/grift-medium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/grift-semibold.otf",
      weight: "600",
      style: "normal",
    },
    {
      path: "./fonts/grift-bold.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/grift-extrabold.otf",
      weight: "800",
      style: "normal",
    },
    {
      path: "./fonts/grift-black.otf",
      weight: "900",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Simba",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${griftSans.className} h-full antialiased`}>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
